force-app/main/default/objects/Exchange__c/Exchange__c.object-meta.xml
<CustomObject>
    <label>Exchange</label>
    <nameField>
        <displayFormat>Exc- {0000}</displayFormat>
        <label>Exchange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTC</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>BYR</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExchangeSettings__mdt/ExchangeSettings__mdt.object-meta.xml
<CustomObject>
    <label>ExchangeSettings</label>
    <pluralLabel>ExchangeSettings</pluralLabel>
</CustomObject>

force-app/main/default/classes/TrReview/Extra/ExchangeRestCallout.cls
public with sharing class ExchangeRestCallout {
    static string Excahange_Endpoint = ExchangeSettings__mdt.getInstance('CalloutSettings').EndPoint__c;
    static string Excahange_ApiKey = ExchangeSettings__mdt.getInstance('CalloutSettings').ApiKey__c;
    static string defaultCurrceny = UserInfo.getDefaultCurrency();
  
    @invocableMethod (label='Exchange Callouts' 
    description='Bu Method callout sonrasi exchnage rate alanini update eder' 
    category='Exchange')
    public static void getExchangeRate(List<Id> exchangeIds){

        List<Exchange__c> listExchange = [SELECT Currency__c, Exchange_Rate__c FROM Exchange__c WHERE Id IN : exchangeIds ];
        List<Exchange__c> updateExchangeList = new List<Exchange__c>();
        for (Exchange__c exc : listExchange) {
            
            string currencyField = exc.Currency__c;

            HttpRequest request = new HttpRequest();
            request.setMethod('GET');

            // https://api.apilayer.com/exchangerates_data/latest?symbols=TRY&base=EUR
            request.setEndPoint(Excahange_Endpoint + 'symbols=' + currencyField + '&base=' + defaultCurrceny);
            request.setHeader('apikey', Excahange_ApiKey);
            
            HTTP http = new HTTP();
            HttpResponse response = http.send(request);

            String jsonString = response.getBody();
            system.debug(jsonString);
            if(response.getStatusCode() == 200){
                ExchangeWrapper.rates wrapper = (ExchangeWrapper.rates)JSON.deserialize(jsonString,ExchangeWrapper.rates.class);

                decimal exchangeRate = wrapper.rates.get(currencyField);
                exc.Exchange_Rate__c = exchangeRate;
                updateExchangeList.add(exc);
            }
        }
        try {
            update updateExchangeList;
        } catch (Exception ex) {
            System.debug(ex.getMessage());
        }
    }
}