force-app/main/default/objects/Account/fields/CasesThroughEmail__c.field-meta.xml
<CustomField>
    <fullName>CasesThroughEmail__c</fullName>
    <label>Cases Through Email</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CasesThroughPhone__c.field-meta.xml
<CustomField>
    <fullName>CasesThroughPhone__c</fullName>
    <label>Cases Through Phone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CasesThroughWeb__c.field-meta.xml
<CustomField>
    <fullName>CasesThroughWeb__c</fullName>
    <label>Cases Through Web</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/engReview/Scenario Based/2.1/AccountProcessor.cls
public with sharing class AccountProcessor {
   
    @future
    public static void processAccounts(List<Id> accountIds) {
        //collect all the accounts along with its cases
        List<Account> accounts=[SELECT Id, CasesThroughEmail__c,CasesThroughPhone__c,CasesThroughWeb__c,
                                (SELECT Id, Origin FROM Cases)
                                FROM Account
                                WHERE Id IN:accountIds];

        //iterate over the accounts and its respective cases to count them by category
        for (Account acc : accounts) {
            Integer web=0;
            Integer phone=0;
            Integer email=0;
            for (Case cs : acc.Cases) {
                if (cs.Origin=='Web') {
                    web++;
                } else if(cs.Origin=='Phone') {
                    phone++;
                }else if(cs.Origin=='Email'){
                    email++;
                }
            }
            acc.CasesThroughEmail__c=email;
            acc.CasesThroughPhone__c=phone;
            acc.CasesThroughWeb__c=web;


        }

        //update accounts
        try {
            update accounts;

        } catch (Exception ex) {
            //create log
            System.debug(ex.getMessage());
        }
    }
}