force-app/main/default/objects/Account/fields/MaxSalary__c.field-meta.xml
<CustomField>
    <fullName>MaxSalary__c</fullName>
    <label>Max Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/TotalSalary__c.field-meta.xml
<CustomField>
    <fullName>TotalSalary__c</fullName>
    <label>Total Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountSalary__c/AccountSalary__c.object-meta.xml
<CustomObject>
    <label>Account Salary</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Salary#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Salaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountSalary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Salaries</relationshipLabel>
    <relationshipName>AccountSalaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/engReview/Scenario Based/1.4/AccountSalaryHandler.cls
public with sharing class AccountSalaryHandler {
    public static void afterInsert (List<AccountSalary__c>newSalaries){
        Set<Id> accountsIds=new Set<Id>();
        //iterate over salary records & collect their parent account ids
        for (AccountSalary__c sal : newSalaries) {
            accountsIds.add(sal.Account__c);
        }

        //get all the accounts along with its children salary records
        List<Account> accounts=[SELECT Id, TotalSalary__c, MaxSalary__c,
                                (SELECT Id, Account__c, Salary__c FROM AccountSalaries__r)
                                FROM Account
                                WHERE Id IN:accountsIds];
        for (Account acc : accounts) {
            Decimal total=0.0;
            Decimal max=0.0;
            for (AccountSalary__c sal : acc.AccountSalaries__r) {
                if (max<sal.Salary__c) {
                    max=sal.Salary__c;
                }
                total=total+sal.Salary__c;
            }
            acc.TotalSalary__c=total;
            acc.MaxSalary__c=max;
        }

        //update accounts
        try {
            update accounts;
        } catch (Exception ex) {
            //create log
            System.debug(ex.getMessage());
        }
    }
}