force-app/main/default/objects/Account/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/TotalOpps__c.field-meta.xml
<CustomField>
    <fullName>TotalOpps__c</fullName>
    <label>Total Opps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/engReview/Scenario Based/1.2/OpportunityHandler.cls
public with sharing class OpportunityHandler {
    public static void afterInsert(List<Opportunity> newOpps){
        Set<Id> accountIds=new Set<Id>();

        //iterate over new opps and collect parent accounts
        for (Opportunity opp : newOpps) {
            if (opp.AccountId !=Null) {
                accountIds.add(opp.AccountId);
            }
        }

        //Calculate total opps & total amounts
        updateAccounts(accountIds);
    }

    private static void updateAccounts(Set<Id>accountIds){
        //get the accounts along with children opps
        List<Account> accounts=[SELECT Id,TotalOpps__c, TotalAmount__c, (SELECT Id, Amount FROM Opportunities)
                                FROM Account
                                WHERE ID IN :accountIds];

        for (Account acc : accounts) {
            acc.TotalOpps__c=acc.Opportunities.size();

            Decimal total=0;
            for(Opportunity opp:acc.Opportunities){
                total += opp.Amount;
            }
            acc.TotalAmount__c=total;
        }
        //update accounts
        if (!accounts.isEmpty()) {
            try {
                update accounts;
            } catch (Exception ex) {
                //create a log
                
            }
        }
    
    }
}