force-app/main/default/objects/Customer__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments__c/Payments__c.object-meta.xml
<CustomObject>
    <label>Payments</label>
    <nameField>
        <displayFormat>p-{0000}</displayFormat>
        <label>Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrReview/12.Ders/PaymentTriggerHandler.cls
public with sharing class PaymentTriggerHandler {
    
    public static void updateAmountOnPaymentInsert(List<Payments__c> triggerNew){

        Set<Id> customersIdsSet = new  Set<Id>(); 
        for (Payments__c pym : triggerNew) {
            if (pym.Amount__c!=null) {
                customersIdsSet.add(pym.Customer__c); 
                
            }
        }

        if (!customersIdsSet.isEmpty()) {

            updateAmountOnCustomer(customersIdsSet);
    }
}
    public static void updateAmountOnPaymentUpdate(List<Payments__c> triggerNew, Map<Id, Payments__c> triggerOldMap){

        Set<Id> customersIdsSet = new  Set<Id>(); 
        for (Payments__c p : triggerNew) {
            Payments__c oldRec = triggerOldMap.get(p.Id);
            if ((p.Amount__c != oldRec.Amount__c || p.Customer__c!=oldRec.Customer__c) && p.Amount__c!=null) {
                customersIdsSet.add(p.Customer__c);
                customersIdsSet.add(oldRec.Customer__c);
            }

            if (!customersIdsSet.isEmpty()) {

                updateAmountOnCustomer(customersIdsSet);
        }
        }
    }

    public static void updateAmountOnPaymentDelete(List<Payments__c> triggerOld){

            Set<Id> customersIdsSet = new  Set<Id>(); 
            for (Payments__c pym : triggerOld) {
                if (pym.Amount__c!=null) {
                    customersIdsSet.add(pym.Customer__c); 
                    
                }
            }

            if (!customersIdsSet.isEmpty()) {

                updateAmountOnCustomer(customersIdsSet);
        }
    }

    public static void updateAmountOnPaymentUnDelete(List<Payments__c> triggerNew){

        Set<Id> customersIdsSet = new  Set<Id>(); 
        for (Payments__c pym : triggerNew) {
            if (pym.Amount__c!=null) {
                customersIdsSet.add(pym.Customer__c); 
                
            }
        }

        if (!customersIdsSet.isEmpty()) {

            updateAmountOnCustomer(customersIdsSet);
    }
}







    public static void updateAmountOnCustomer(Set<id> customersIdsSet){

        List<Customer__c> customerRelatedPayment = [SELECT Id, Total_Amount__c, (SELECT Id, Amount__c FROM Payments__r) FROM Customer__c WHERE Id IN :customersIdsSet];

        List<Customer__c> updatedCustomerList = new List<Customer__c>();

        for (Customer__c c : customerRelatedPayment) {
            Decimal totalAmount = 0 ;
            for (Payments__c p : c.Payments__r) {
                totalAmount = totalAmount + p.Amount__c;
            }
            c.Total_Amount__c = totalAmount;
            updatedCustomerList.add(c);
        }
        if (!updatedCustomerList.isEmpty()) {
            update updatedCustomerList; 
        }
    }
}